schema: 1
domain: 137-66-9-53.sslip.io

runtime:
  startup_wait: 25s
  status_idle_exit: 30s
  empty_before_switch: 2m
  idle_before_stop: 10m
  backend_poll_interval: 10s
  shutdown_timeout: 2m
  max_connections: 128
  connections_per_minute: 30
  listen_address: ":25565"
  backend_address: "127.0.0.1:25566"

capacity:
  memory_mb: 8192
  cpus: 4

storage:
  driver: s3
  evict_after_backup: true
  s3:
    endpoint: https://fly.storage.tigris.dev
    region: auto
    bucket: mchostpack-urz-worlds-v2
    prefix: hostpack/worlds

packs:
  sfs:
    display_name: Standard Fabric Server 1.21.1
    provider: modrinth
    project_id: r5ygbOIe
    version_id: FCnyrYJ4
    java: 21
    memory_mb: 1536
    machine_memory_mb: 2048
    machine_cpus: 2
  cobblemon:
    display_name: Cobblemon Official NeoForge 1.7.3
    provider: modrinth
    project_id: mHMxXbIu
    version_id: VJ9Jur2k
    java: 21
    memory_mb: 3072
    machine_memory_mb: 4096
    machine_cpus: 2
